repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
repos:
-   repo: https://github.com/python-poetry/poetry
    rev: '1.7.1'  # add version here
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
    -   id: poetry-export
    -   id: poetry-install